source 'https://rubygems.org'

gem 'jekyll', '~> 4.2'
gem 'jekyll-feed'
gem 'jekyll-redirect-from'
gem 'jemoji'
gem 'jekyll-sitemap'
gem 'jekyll-seo-tag'
gem 'jekyll-avatar'
gem 'jekyll-gist'
gem 'jekyll-multiple-languages-plugin'
gem 'webrick', '~> 1.8'
